# -*- coding: utf-8 -*-
"""pemvis pt9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JzDf5xUb2oP9Xid_eBuhxHVpXP2LbR-4
"""

import tkinter as tk

root = tk.Tk()

Frameku = tk.Frame(root, bg = 'blue')
Frameku.place(relwidth = 0.8, relheight = 0.8)

root.mainloop()

Tombolku = tk.Button(Frameku, Text = "Tes Tombol", bg = 'gray', fg = 'red')
Tombolku.pack()

Entryku = tk.Entry(Frameku, bg = 'green')
Entryku.pack()

root.mainloop()